const NEIGHBORHOODS_BY_CITY: Readonly<Record<string, readonly string[]>> = {
  Sorocaba: [
    'Além Linha',
    'Além Ponte',
    'Alto da Boa Vista',
    'Altos de Ipanema',
    'Ana Maria',
    'Aparecida',
    'Aparecidinha',
    'Área Industrial',
    'Bairro da Vossoroca',
    'Boa Vista',
    'Brigadeiro Tobias',
    'Caguassu',
    'Cajuru do Sul',
    'Campininha',
    'Caputera',
    'Central Parque Sorocaba',
    'Centro',
    'Centro Empresarial Sorocaba',
    'Cerrado',
    'Chácara Recanto Silvestre',
    'Chácara Três Marias',
    'Chácaras Reunidas São Jorge',
    'Cidade Jardim',
    'Complexo Viário Governador Mário Covas',
    'Condomínio Residencial Terras de São Lucas',
    "Condomínio Residencial Village D'Avignon",
    'Condomínio Residencial Village Vert',
    'Conjunto Habitacional Doutor Ulisses Guimarães',
    'Conjunto Habitacional Herbert de Souza',
    'Conjunto Habitacional Júlio de Mesquita Filho',
    'Conjunto Habitacional Professor Benedicto Cleto',
    'Conjunto Residencial Jardim Villagio Torino',
    'Distrito Industrial',
    'Éden',
    'Fazenda Genebra',
    'Genebra',
    'Granja Olga I',
    'Granja Olga II',
    'Granja Olga III',
    'Habiteto - Ana Paula Eleutério',
    'Horto Florestal',
    'Ibiti Royal Park',
    'Inhayba',
    'Ipanema das Pedras',
    'Ipanema do Meio',
    'Ipanema Ville',
    'Ipatinga',
    'Ipiranga',
    'Iporanga',
    'Iporanga II',
    'Itapeva',
    'Itavuvu',
    'Itinga',
    'Jardim Abaeté',
    'Jardim Abatiá',
    'Jardim Aeroporto',
    'Jardim Alegria',
    'Jardim Alpes de Sorocaba',
    'Jardim Altos do Itavuvu',
    'Jardim Alvorada',
    'Jardim Amalia',
    'Jardim América',
    'Jardim Americano',
    'Jardim Ametista',
    'Jardim Ana Maria',
    'Jardim Astro',
    'Jardim Atílio Silvano',
    'Jardim Avore Pilungo',
    'Jardim Bandeirantes',
    'Jardim Bela Vista',
    'Jardim Belvedere',
    'Jardim Bermejo',
    'Jardim Bertanha',
    'Jardim Betânia',
    'Jardim Boa Esperança',
    'Jardim Boa Vista',
    'Jardim Bonsucesso',
    'Jardim Botânico',
    'Jardim Botucatu',
    'Jardim Brasilândia',
    'Jardim Califórnia',
    'Jardim Cambará',
    'Jardim Camila',
    'Jardim Campos do Conde II',
    'Jardim Capitão',
    'Jardim Carandá',
    'Jardim Cardoso',
    'Jardim Carolina',
    'Jardim Casa Branca',
    'Jardim Casagrande',
    'Jardim Celeste',
    'Jardim Colina Verde',
    'Jardim Constantino Matucci',
    'Jardim Copaíba',
    'Jardim Cruz de Ferro',
    'Jardim Cruzeiro do Sul',
    'Jardim Dacha Sorocaba',
    'Jardim das Acácias',
    'Jardim das Azaléias',
    'Jardim das Estrelas',
    'Jardim das Flores',
    'Jardim das Magnólias',
    'Jardim das Orquídeas',
    'Jardim Didita',
    'Jardim do Carmo',
    'Jardim do Paço',
    'Jardim do Sol',
    'Jardim Dois Corações',
    'Jardim Dona Tereza',
    'Jardim dos Estados',
    'Jardim dos Pássaros',
    'Jardim Eden Ville',
    'Jardim Edgar Marques',
    'Jardim Eliana',
    'Jardim Eltonville',
    'Jardim Embaixador',
    'Jardim Emília',
    'Jardim Eucalíptos',
    'Jardim Europa',
    'Jardim Excelsior',
    'Jardim Faculdade',
    'Jardim Ferreira',
    'Jardim Flamboyant',
    'Jardim Francini',
    'Jardim Germiniani',
    'Jardim Golden Park Residence',
    'Jardim Golden Park Residence II',
    'Jardim Golden Park Residencial',
    'Jardim Gonçalves',
    'Jardim Gramados de Sorocaba',
    'Jardim Granja Deolinda',
    'Jardim Guadalajara',
    'Jardim Guadalupe',
    'Jardim Guaíba',
    'Jardim Gualberto Moreira',
    'Jardim Guarujá',
    'Jardim Gutierres',
    'Jardim Harmonia',
    'Jardim Helena Cristina',
    'Jardim Henrique',
    'Jardim Horizonte',
    'Jardim Humberto de Campos',
    'Jardim Hungares',
    'Jardim Ibiti do Paço',
    'Jardim Iguatemi',
    'Jardim Imperial',
    'Jardim Ipanema',
    'Jardim Ipê',
    'Jardim Isaura',
    'Jardim Itaipu',
    'Jardim Itália',
    'Jardim Itanguá',
    'Jardim Itanguá II',
    'Jardim Itapemirim',
    'Jardim Itapuã',
    'Jardim J S Carvalho',
    'Jardim Jatobá',
    'Jardim Josane',
    'Jardim Judith',
    'Jardim Juliana',
    'Jardim Leandro Dromani',
    'Jardim Leocádia',
    'Jardim Liberdade',
    'Jardim Los Angeles',
    'Jardim Luciana Maria',
    'Jardim Marcelo Augusto',
    'Jardim Marco Antônio',
    'Jardim Maria Antônia Prado',
    'Jardim Maria Cristina',
    'Jardim Maria do Carmo',
    'Jardim Maria Elvira',
    'Jardim Maria Eugênia',
    'Jardim Marli',
    'Jardim Marnilda',
    'Jardim Millenium',
    'Jardim Monte Carlo',
    'Jardim Monte Hey',
    'Jardim Monteiro',
    'Jardim Monterrey',
    'Jardim Montevidéo',
    'Jardim Montreal',
    'Jardim Morumbi',
    'Jardim Nair',
    'Jardim Nápoli',
    'Jardim Nelisa',
    'Jardim Nilton Torres',
    'Jardim Nogueira',
    'Jardim Nova Aparecidinha',
    'Jardim Nova Astúrias',
    'Jardim Nova Esperança',
    'Jardim Nova Ipanema',
    'Jardim Nova Manchester',
    'Jardim Nova Tupã',
    'Jardim Novo Bandeirantes',
    'Jardim Novo Eldorado',
    'Jardim Novo Horizonte',
    'Jardim Novo Mundo',
    'Jardim Pacaembu',
    'Jardim Pagliato',
    'Jardim Panamericano Condomínio Empresarial (Área D)',
    'Jardim Panorama',
    'Jardim Parada do Alto',
    'Jardim Paraíso',
    'Jardim Paraná',
    'Jardim Paulista',
    'Jardim Paulistano',
    'Jardim Pelegrino',
    'Jardim Piazza di Roma',
    'Jardim Piazza Di Roma II',
    'Jardim Piratininga',
    'Jardim Pires de Mello',
    'Jardim Pitangui',
    'Jardim Planalto',
    'Jardim Portal da Colina',
    'Jardim Portal da Primavera',
    'Jardim Portal do Itavuvu',
    'Jardim Portobello',
    'Jardim Portugal',
    'Jardim Prestes de Barros',
    'Jardim Primavera',
    'Jardim Real',
    'Jardim Refúgio',
    'Jardim Regente',
    'Jardim Renascer',
    'Jardim Reserva Ipanema',
    'Jardim Reserva Ipanema 2',
    'Jardim Residencial Campos do Conde',
    'Jardim Residencial Carmem Blanco',
    'Jardim Residencial Castanheira',
    'Jardim Residencial Chácara Ondina',
    'Jardim Residencial Colinas do Sol',
    'Jardim Residencial das Dálias',
    'Jardim Residencial Deolinda Guerra',
    'Jardim Residencial dos Reis',
    'Jardim Residencial Giverny',
    'Jardim Residencial Guaporé',
    'Jardim Residencial Helena Maria',
    'Jardim Residencial Horizontes de Sorocaba',
    'Jardim Residencial Imperatriz',
    'Jardim Residencial Jardim',
    'Jardim Residencial Júlia Martinez',
    'Jardim Residencial Le France',
    'Jardim Residencial Martinez',
    'Jardim Residencial Mont Blanc',
    'Jardim Residencial Morada das Artes',
    'Jardim Residencial Morada das Flores',
    'Jardim Residencial Nikkey',
    'Jardim Residencial Pampulha',
    'Jardim Residencial Renascence',
    'Jardim Residencial Saint Patrick',
    'Jardim Residencial Saint Patrick 2',
    'Jardim Residencial Santinon',
    'Jardim Residencial Sunset Village',
    'Jardim Residencial Tivoli Park',
    'Jardim Residencial Vale Verde',
    'Jardim Residencial Vicente de Moraes',
    'Jardim Residencial Villa Amato',
    'Jardim Residencial Villa Olympia',
    'Jardim Residencial Villa Suiça',
    'Jardim Residencial Villagio Ipanema I',
    'Jardim Residencial Villagio Ipanema II',
    'Jardim Residencial Villagio Wanel',
    'Jardim Residencial Vittório Emanuelle',
    'Jardim Residencial Vivenda do Itavuvu',
    'Jardim Residencial Vivendas do Lago II',
    'Jardim Rodrigo',
    'Jardim Rosália Alcolea',
    'Jardim Rubi',
    'Jardim Saira',
    'Jardim Sandra',
    'Jardim Santa Bárbara',
    'Jardim Santa Catarina',
    'Jardim Santa Cecília',
    'Jardim Santa Claudia',
    'Jardim Santa Esmeralda',
    'Jardim Santa Fé',
    'Jardim Santa Helena',
    'Jardim Santa Lúcia',
    'Jardim Santa Luiza',
    'Jardim Santa Madre Paulina',
    'Jardim Santa Marina',
    'Jardim Santa Marina II',
    'Jardim Santa Marta',
    'Jardim Santa Paula',
    'Jardim Santa Paula II',
    'Jardim Santa Rosa',
    'Jardim Santa Rosália',
    'Jardim Santo Amaro',
    'Jardim Santo André',
    'Jardim Santo André II',
    'Jardim São Camilo',
    'Jardim São Carlos',
    'Jardim São Conrado',
    'Jardim São Guilherme',
    'Jardim São Judas Tadeu',
    'Jardim São Lourenzo',
    'Jardim São Marcos',
    'Jardim São Marcos II',
    'Jardim São Paulo',
    'Jardim Simus',
    'Jardim Siriema',
    'Jardim Sol Nascente',
    'Jardim Solar do Bosque',
    'Jardim Sônia Maria',
    'Jardim Sorocaba Park',
    'Jardim Sorocabano',
    'Jardim Tatiana',
    'Jardim Terras de São Francisco',
    'Jardim Topázio',
    'Jardim Tortelli',
    'Jardim Tropical',
    'Jardim Tulipas',
    'Jardim Tupinambá',
    'Jardim Turmalina',
    'Jardim Vale do Lago Residencial',
    'Jardim Vera Cruz',
    'Jardim Vergínia',
    'Jardim Vergueiro',
    'Jardim Via Reggio',
    'Jardim Vila Inglesa',
    'Jardim Vila São Domingos',
    'Jardim Villa Verona',
    'Jardim Village Saint Claire',
    'Jardim Villagio Milano',
    'Jardim Wanel Ville I',
    'Jardim Wanel Ville IV',
    'Jardim Wanel Ville V',
    'Jardim Zezo Miguel',
    'Jardim Zulmira',
    'João Camargo',
    'Lopes de Oliveira',
    'Loteamento Dinorá Rosa',
    'Loteamento Farmacêutico',
    'Loteamento Jardim Residencial Tereza Maria',
    'Metropolitano Condomínio Empresarial',
    'Morros',
    'Núcleo Habitacional Jardim Itapemirim',
    'Núcleo Habitacional Tupã II',
    'Parque Campolim',
    'Parque das Laranjeiras',
    'Parque das Paineiras',
    'Parque dos Eucaliptos',
    'Parque Ecoresidencial Fazenda Jequitibá',
    'Parque Empresarial das Mangueiras',
    'Parque Esmeralda',
    'Parque Ibiti Reserva',
    'Parque Industrial Prestes (Éden)',
    'Parque Manchester',
    'Parque Ouro Fino',
    'Parque Reserva Fazenda Imperial',
    'Parque Residencial Villa dos Inglezes',
    'Parque Santa Isabel',
    'Parque São Bento',
    'Parque Tecnológico de Sorocaba',
    'Parque Três Meninos',
    'Parque Vereda Bandeirantes',
    'Parque Vista Barbara',
    'Parque Vitória Régia',
    'Pitas',
    'Portal de São Francisco',
    'Quintais do Imperador',
    'Rancho Dirce',
    'Recanto do Jataí',
    'Recanto dos Juritis',
    'Recreio dos Sorocabanos',
    'Recreio Marajoara',
    'Residencial Bosque Ipanema',
    'Residencial Chácara da Planície',
    'Residencial Horto Florestal Villagio',
    'Residencial Jardim Bounganville',
    'Residencial Jardim Nathália',
    'Residencial Jardim Villagio Sola',
    'Residencial Villa do Bosque',
    'Residencial Villazul',
    'Retiro São João',
    'Ronda',
    'Sorocaba 1',
    'Tapera Grande',
    'Terras de Arieta',
    'Tijuco Preto',
    'Vila Acácia Marina',
    'Vila Adélia',
    'Vila Aeroporto',
    'Vila Almeida',
    'Vila Amélia',
    'Vila Ana Maria',
    'Vila Angélica',
    'Vila Antão',
    'Vila Artura',
    'Vila Assis',
    'Vila Augusta',
    'Vila Barão',
    'Vila Barcelona',
    'Vila Bom Jesus',
    'Vila Borghesi',
    'Vila Carvalho',
    'Vila Casanova',
    'Vila Cássia Maria',
    'Vila Colorau',
    'Vila da Fonte',
    'Vila Dálmatas',
    'Vila Elza',
    'Vila Eros',
    'Vila Esperança',
    'Vila Espírito Santo',
    'Vila Fiori',
    'Vila Fleury',
    'Vila Florinda',
    'Vila Formosa',
    'Vila Gabriel',
    'Vila Gomes',
    'Vila Guilherme',
    'Vila Guimarães',
    'Vila Hanickel',
    'Vila Haro',
    'Vila Helena',
    'Vila Hortência',
    'Vila Independência',
    'Vila Jardini',
    'Vila João Romão',
    'Vila Josefina',
    'Vila Leão',
    'Vila Leopoldina',
    'Vila Louzada',
    'Vila Lucy',
    'Vila Marina Dias',
    'Vila Marta',
    'Vila Melges',
    'Vila Mineirão',
    'Vila Netinho',
    'Vila Nicanor Marques',
    'Vila Nova Sorocaba',
    'Vila Odim Antão',
    'Vila Odin',
    'Vila Olímpia',
    'Vila Primavera',
    'Vila Progresso',
    'Vila Rica',
    'Vila Rodrigues',
    'Vila Sabiá',
    'Vila Santa Francisca',
    'Vila Santa Rita',
    'Vila Santa Tereza',
    'Vila Santana',
    'Vila São Bernardo',
    'Vila São Caetano',
    'Vila São João',
    'Vila São Jorge',
    'Vila Soares',
    'Vila Sônia',
    'Vila Teodolinda',
    'Vila Terron',
    'Vila Tortelli',
    'Vila Trujillo',
    'Vila Zacarias',
    'Village Cajuru',
    'Vivendas do Lago',
    'Wanel Ville',
    'Zona Industrial',
  ],
  Votorantim: [
    'Alphaville Nova Esplanada',
    'Alphaville Nova Esplanada 3',
    'Alphaville Nova Esplanada 4',
    'Altos da Fortaleza',
    'Altos de Votorantim',
    'Área Industrial',
    'Barra Funda',
    'Bosque São Francisco',
    'Capoavinha',
    'Carafá',
    'Centro',
    'Chácaras Leão',
    'Chácaras Residenciais Santa Maria',
    'Chave',
    'Colina Santa Mônica',
    'Condomínio Residencial Flores',
    'Conjunto Habitacional Augustinho Kriguer',
    'Conjunto Habitacional Jardim Serrano',
    'Conjunto Habitacional Santa Maria',
    'Conjunto Habitacional Votorantim C',
    'Cortume',
    'Cyrela Landscape Esplanada',
    'Fornazari',
    'Green Valley',
    'Ipanema das Pedras',
    'Itapeva',
    'Jardim Ana Claudia',
    'Jardim Antônio Cassillo',
    'Jardim Antônio Rodrigues e Rodrigues',
    'Jardim Araújo',
    'Jardim Archila',
    'Jardim Bandeirantes',
    'Jardim Bertioga',
    'Jardim Clarice I',
    'Jardim Daniel Antônio',
    'Jardim das Colinas',
    'Jardim Devito',
    'Jardim Europa',
    'Jardim Icatu',
    'Jardim Karolyne',
    'Jardim Maria José',
    'Jardim Maria Lúcia',
    'Jardim Mirante dos Ovnis',
    'Jardim Monte Sião',
    'Jardim Novo Mundo',
    'Jardim Palmira',
    'Jardim Paraíso',
    'Jardim Paulista',
    'Jardim Primavera',
    'Jardim Residencial Chácara Ondina',
    'Jardim Santo Antônio I',
    'Jardim Santo Antônio II',
    'Jardim São Lucas',
    'Jardim São Luís',
    'Jardim São Matheus',
    'Jardim São Pedro',
    'Jardim Sarkis Abibe',
    'Jardim Serrano',
    'Jardim Serrano II',
    'Jardim Simone',
    'Jardim Tatiana',
    'Jardim Toledo',
    'Jardim União',
    'Loteamento Aldeia da Mata',
    'Loteamento Jardim Nova Votorantim',
    'Loteamento Residencial Villágio Di Capri',
    'Loteamento Sunlake SPA Residencial',
    'Morros',
    'Nova Votorantim',
    'Parque Bela Vista',
    'Parque Esplanada',
    'Parque Jataí',
    'Parque Morumbi',
    'Parque Santa Márcia',
    'Parque Santos Dumont',
    'Parque São João',
    'Pro-Morar',
    'Protestantes',
    'Real Parque',
    'Real Parque II',
    'Real Parque IV',
    'Residencial Cristal',
    'Residencial Giardino Di Veneto',
    'Residencial Monte Verde',
    'Residencial Serra Dourada',
    'Residencial Vasques Martins',
    'Residencial Votorantim Park I',
    'Residencial Votorantim Park II',
    'Rio Acima',
    'Vale do Sol',
    'Vila Aldo Damini',
    'Vila Amorim',
    'Vila Angelo Vial',
    'Vila Domingues',
    'Vila Dominguinho',
    'Vila Dylze',
    'Vila Gali',
    'Vila Guilherme',
    'Vila Helena',
    'Vila Irineu',
    'Vila José Ramos',
    'Vila Mercedes',
    'Vila Pardini',
    'Vila Pedroso',
    'Vila Rodrigues',
    'Vila Santo Antônio',
    'Vila São José',
    'Vila Vasques',
    'Vila Votocel',
    'Villa Bella de Votorantim',
    'Villa Toscana',
    'Vivalegro',
    'Vossoroca',
  ],
  Itu: [
    'Alphaville Itu',
    'Alto',
    'Alto da Vila Nova',
    'Alto das Palmeiras',
    'Altos de Itu',
    'Apotribu de Cima',
    'Bairro Campos de Santo Antônio',
    'Beira Rio',
    'Braiaia',
    'Brasil',
    'Campininha',
    'Canguiri',
    'Canjica',
    'Centro',
    'Centro Empresarial Castelo',
    'Chácara Bela Vista',
    'Chácara Carolina',
    'Chácara dos Eucaliptos',
    'Chácara Flora',
    'Chácara Flórida',
    'Chácara Harmonia I',
    'Chácara Harmonia II',
    'Chácara Palma',
    'Chácara Paraíso',
    'Chácara Residencial Paraíso Marriot',
    'Chácara São João',
    'Chácara Sete Quedas',
    'Chácaras Agrícolas Bandeirantes',
    "Chácaras Berro D'Água",
    'Chácaras Leonardi',
    'Chácaras Monte Verde',
    'Chácaras Primavera',
    'Chácaras Reunidas Ipê',
    'Chácaras Rincão',
    'Chácaras Shamballa Village',
    'Chafaris',
    'Cidade Nova I',
    'Cidade Nova II',
    'City Castello',
    'Condomínio Bethaville Empresarial 3',
    'Condomínio Fechado Bothanica Itu',
    'Condomínio Portal de Itu',
    'Condomínio Residencial Mont Blanc',
    'Condomínio Terras de São José',
    'Conjunto Habitacional União',
    'Cruz das Almas',
    'Estância Vila Verde',
    'Fazenda da Mata',
    'Fazenda Vila Real de Itu',
    'Granjas Bela Vista',
    'Itaim',
    'Itaim Guaçu',
    'Itaim Mirim',
    'Itu Novo Centro',
    'Jardim Aeroporto I',
    'Jardim Aeroporto II',
    'Jardim Agarussi',
    'Jardim Alberto Gomes',
    'Jardim Brasília',
    'Jardim Convenção',
    'Jardim Corazza',
    'Jardim da Vitória',
    'Jardim das Indústrias',
    'Jardim das Rosas',
    'Jardim do Estádio',
    'Jardim dos Ipês',
    'Jardim Emicol',
    'Jardim Encanto do Jacuhu',
    'Jardim Eridano',
    'Jardim Estância Bom Viver',
    'Jardim Europa',
    'Jardim Faculdade',
    'Jardim Madre Paulina',
    'Jardim Novo Itu',
    'Jardim Novo Mundo',
    'Jardim Oliveira',
    'Jardim Padre Bento',
    'Jardim Paineiras',
    'Jardim Paraíso',
    'Jardim Paraíso II',
    'Jardim Paulista',
    'Jardim Paulista II',
    'Jardim Paulista III',
    'Jardim Pedreira',
    'Jardim Penha de França',
    'Jardim Plaza Athénée',
    'Jardim Residencial Garden Ville',
    'Jardim Residencial Itaim',
    'Jardim Rosinha',
    'Jardim Santa Laura',
    'Jardim Santa Monica',
    'Jardim Santa Rosa',
    'Jardim Santa Tereza',
    'Jardim Santana',
    'Jardim Santos Dumont',
    'Jardim São Jorge',
    'Jardim São José',
    'Jardim Theodora',
    'Jardim Vila Verde I',
    'Jardim Vila Verde II',
    'Jardim Villas do Golf',
    'Kurumin',
    'Liberdade',
    'Loteamento Eldorado',
    'Loteamento Empresarial JPH',
    'Loteamento Jardim Mirante',
    'Loteamento Jardim Paulista IV',
    'Loteamento Jardim Residencial Paulo Japur',
    'Loteamento Parque Chapada de Itu',
    'Loteamento Portal de São Tiago',
    'Loteamento Residencial Buona Vita',
    'Loteamento Residencial Parque Terras de Santa Cecília',
    'Loteamento Residencial Recanto dos Eucaliptos',
    'Loteamento Residencial Una',
    'Loteamento Residencial Vila das Hortênsias',
    'Loteamento Residencial Vila Turim',
    'Loteamento Terras de Santa Elizabeth',
    'Mangueiras de Itu',
    'Melissa',
    'Nossa Senhora Aparecida',
    'Núcleo Habitacional São Judas Tadeu',
    'Núcleo Industrial Jardim Porto Seguro',
    'Parque América',
    'Parque das Indústrias',
    'Parque das Rosas',
    'Parque do Varvito',
    'Parque Industrial',
    'Parque Nossa Senhora da Candelária',
    'Parque Residencial Guitti',
    'Parque Residencial Mayard',
    'Parque Residencial Potiguara',
    'Parque Residencial Presidente Médici',
    'Parque Residencial Quinta das Laranjeiras',
    'Parque São Camilo',
    'Parque Village Castelo',
    'Pedregulho',
    'Pinheirinho',
    'Pirapitingui',
    'Portal da Vila Rica',
    'Portal do Éden',
    'Portal dos Sabiás',
    'Progresso',
    'Rancho Grande',
    'Residencial Bom Jardim',
    'Residencial Dona Lila',
    'Residencial Dona Tonica',
    'Residencial Itaim II',
    'Residencial Parque Campos de Santo Antônio II',
    'Residencial Rio Araguaia',
    'Residencial Saint Paul',
    'Residencial Santo Inácio',
    'Residencial Sete Quedas',
    'Residencial Veneto',
    'Residencial Vila dos Manacás',
    'Residencial Vila dos Manacás II',
    'Santa Cruz',
    'Santa Inês',
    'São Luiz',
    'Tapera Grande',
    'Taperinha',
    'Terras de Santa Carolina',
    'Terras de Santa Carolina II',
    'Terras de Santa Maria I',
    'Terras de Santa Maria II',
    'Terras de São José Urbano Portella',
    'Varejão',
    'Vila Bandeirantes',
    'Vila Cleto',
    'Vila da Paz',
    'Vila Esperança',
    'Vila Fragnani',
    'Vila Gardiman',
    'Vila Gatti',
    'Vila Guido',
    'Vila Ianni',
    'Vila Leis',
    'Vila Lívia',
    'Vila Lucinda/Romana',
    'Vila Mariáh',
    'Vila Martins',
    'Vila Nova',
    'Vila Padre Bento',
    'Vila Prudente de Moraes',
    'Vila Residencial São Domingos',
    'Vila Roma',
    'Vila Santa Rita',
    'Vila Santa Rosa',
    'Vila Santa Terezinha',
    'Vila São Francisco',
    'Vila São José',
    'Vila São Paulo',
    'Vila Swevia',
    'Vila Vivenda',
  ],
  Salto: [
    'Bela Vista',
    'Boa Vista',
    'Buru',
    'Canjica',
    'Centro',
    'Cesário Loate',
    'Chácara Araújo',
    'Chácara Halter',
    'Chácara Iracema',
    'Chácara Maracajás',
    'Condomínio Fazenda Palmeiras Imperiais',
    'Condomínio Fechado Hermenegildo Milioni',
    'Condomínio Fechado Piccolo Paese',
    'Condomínio Fechado Village Haras São Luiz',
    'Condomínio Fechado Village Haras São Luiz II',
    'Condomínio Monte Belo',
    'Condomínio Zuleika Jabour',
    'Conjunto Habitacional Monte Pascoal',
    'Conjunto Residencial Vila Conte 1',
    'Distrito Industrial',
    'Distrito Industrial do Lageado',
    'Distrito Industrial dos Bandeirantes',
    'Distrito Industrial II',
    'Estação',
    'Estância da Colina',
    'Guaraú',
    'Guaraú II',
    'Haras Paineiras',
    'Industrial Jaraguá',
    'Itapecerica',
    'Jardim Alvorada',
    'Jardim América',
    'Jardim Arco-Íris',
    'Jardim Arquidiocesano',
    'Jardim Bandeirantes',
    'Jardim Barcella',
    'Jardim Bom Retiro',
    'Jardim Brasil',
    'Jardim Buru',
    'Jardim Celani',
    'Jardim Celani II',
    'Jardim da Cidade',
    'Jardim da Cidade II',
    'Jardim da Cidade III',
    'Jardim da Cidade IV',
    'Jardim das Nações',
    'Jardim Delegá',
    "Jardim D'Icaraí",
    'Jardim do Divino',
    'Jardim Donalísio',
    'Jardim dos Ipês',
    'Jardim Eldorado',
    'Jardim Elizabeth',
    'Jardim Europa',
    'Jardim Guarujá',
    'Jardim Imperador',
    'Jardim Independência',
    'Jardim Itaguaçu',
    'Jardim Izaura Maria',
    'Jardim Maria José',
    'Jardim Marília',
    'Jardim Municipal',
    'Jardim Nair Maria',
    'Jardim Nova Era',
    'Jardim Novo São Pedro',
    'Jardim Panorama',
    'Jardim Paraíso',
    'Jardim Planalto',
    'Jardim Primavera',
    'Jardim Saltense',
    'Jardim Saltense II',
    'Jardim Santa Cruz',
    'Jardim Santa Efigênia',
    'Jardim Santa Lúcia',
    'Jardim Santa Marta',
    'Jardim Santa Marta II',
    'Jardim Santa Marta III',
    'Jardim Santa Rita',
    'Jardim Santa Terezinha',
    'Jardim Santo Antônio',
    'Jardim Santo Inácio',
    'Jardim São Francisco',
    'Jardim São Gabriel II',
    'Jardim São João',
    'Jardim São Judas Tadeu',
    'Jardim Sevilha',
    'Jardim Soberano',
    "Jardim Sol D'Icaraí",
    'Jardim Sontag',
    'Jardim Taquaral',
    'Jardim Três Marias',
    'Jardim União',
    'Jardim Villela',
    'Joana Leite',
    'João Jabour',
    'Julio Ustrito',
    'Lajeado',
    'Loteamento Alberto Cintra Filho',
    'Loteamento Industrial e Comercial Corporate Park',
    'Loteamento Jardim das Constelações',
    'Loteamento Santa Edwiges',
    'Loteamento Terras de São Pedro e São Paulo',
    'Micai',
    'Mirante dos Ipês',
    'Nossa Senhora do Monte Serrat',
    'Núcleo Industrial Alert',
    'Olaria',
    'Parque Alto da Boa Vista',
    'Parque Residencial Rondon',
    'Pedregulho',
    'Portal dos Bandeirantes Salto',
    'Porto Góes',
    'Rancho Feliz',
    'Recanto do Guarau',
    'Reserva Central Parque',
    'Residencial Barnabé',
    'Residencial Cata-Vento',
    'Residencial Central Parque',
    'Residencial Costa das Areias II',
    'Residencial do Bosque',
    'Residencial Fabbri',
    "Residencial Lagos D'Icaraí",
    'Residencial Morro da Mata',
    'Residencial Parque Imperial',
    'Residencial Parque Laguna',
    'Residencial Piccolino',
    'Residencial Porto Seguro',
    'Residencial Primavera',
    'Residencial Primavera II',
    'Residencial Salto',
    'Residencial Santa Madre Paulina',
    'Residencial Santo Stéfano',
    'Residencial São Bento',
    'Residencial São Gabriel',
    'Residencial São Valentim',
    'Residencial Vila dos Eucaliptos',
    'Residencial Vila Martins',
    'Residencial Villagio do Conde',
    'Salto de São José',
    'Salto Ville',
    'Seco',
    'Sítio Santa Terezinha',
    'Terras de Mont Serrat',
    'Terras de Santa Izabel',
    'Terras de Santa Rosa',
    'Terras de Santa Rosa II',
    'Vila Flora',
    'Vila Henrique',
    'Vila Ideal',
    'Vila Norma',
    'Vila Nova',
    'Vila Progresso',
    'Vila Roma',
    'Vila Romão',
    'Vila Teixeira',
    'Village Milioni',
    'Village Moutonnée',
  ],
  'Salto de Pirapora': [
    'Alpes do Sarapu',
    'Arco Íris',
    'Boa Vista',
    'Campo Largo',
    'Capão Redondo',
    'Capoavinha',
    'Casa Blanca',
    'Centro',
    'Chácara Recanto',
    'Chácara Reunidas Bela Vista',
    'Chácaras Parque Pirapora',
    'Chácaras Reunidas Dallas',
    'Chácaras Reunidas Eldorado',
    'Chácaras Reunidas Primavera',
    'Corvinho',
    'Da Barra',
    'Distrito Industrial I',
    'Distrito Industrial II',
    'Do Arado',
    'Dos Barros',
    'Dos Castanhos',
    'Dos Leites',
    'Dos Pires',
    'Estância Tropical',
    'Fazendinha',
    'Itinga',
    'Jardim Agenor Leme dos Santos',
    'Jardim Alexandre',
    'Jardim Alvorada',
    'Jardim Amélia',
    'Jardim América',
    'Jardim Ana Guilherme',
    'Jardim Aurea',
    'Jardim Avenida',
    'Jardim Bela Vista',
    'Jardim Cachoeira',
    'Jardim Conde Francisco Matarazzo Júnior',
    'Jardim Daniel David Haddad',
    'Jardim das Bandeiras',
    'Jardim David José Haddad',
    'Jardim Dona Madalena',
    'Jardim Ilha das Flores',
    'Jardim Karina',
    'Jardim Luar',
    'Jardim Maria Clara',
    'Jardim Maria José',
    'Jardim Paulistano',
    'Jardim Primavera',
    'Jardim San Rafael',
    'Jardim Santa Bárbara',
    'Jardim Santa Helena',
    'Jardim Santa Maria',
    'Jardim São Carlos',
    'Jardim São Lucas',
    'Jardim São Lucas II',
    'Jardim São Paulo',
    'Jardim Silva Barros',
    'Jardim Teixeira dos Santos',
    'Jardim Terra Bella',
    'Jardim Vera Lúcia',
    'José Ermírio de Moraes',
    'Jucurupava',
    'Mirante do Sol',
    'Morro Branco',
    'Ourives',
    'Pacaembú Bandeiras',
    'Pacaembú Bandeiras 2',
    'Pirapora',
    'Pirapora Velho',
    'Piraporão',
    'Piraporinha',
    'Portal de Pirapora',
    'Quintas de Pirapora I',
    'Quintas de Pirapora II',
    'Recanto Cidade Nova',
    'Recanto São Manoel I',
    'Recanto São Manoel II',
    'Reserva São José',
    'Residencial Fazenda Alta Vista',
    'Santa Isabel',
    'Sol do Alvorada',
    'Terras de São Francisco',
    'Terras de São João',
    'Vila dos Florianos',
    'Vila Elizabeth',
    'Vila Santa Isabel',
    'Vila Santa Julieta',
    'Vila Xavier',
  ],
  'Araçoiaba da Serra': [
    'Altos do Cercado',
    'Araçoiabinha',
    'Bairro Aparecida',
    'Barreiro',
    'Boa Vista',
    'Bosque dos Eucaliptos',
    'Caminhos de San Conrado',
    'Campina',
    'Campo do Meio',
    'Capanema',
    'Centro',
    'Cercado',
    'Chácara Primavera',
    'Chácara Santa Terezinha',
    'Chácara Santo Antônio',
    'Colégio Velho',
    'Colina do Ipanema',
    'Colinas de Saint Germain',
    'Colinas I',
    'Colinas II',
    'Colônia',
    'Colonial I',
    'Colonial II',
    'Condomínio Fazenda Lago Azul',
    'Condomínio Lago da Serra',
    'Condomínio Parque Raposo Tavares',
    'Condomínio Residencial La Fontana Del Fiori',
    'Condomínio Vila do Sol',
    'Conjunto Habitacional Alcides Vieira',
    'Conjunto Habitacional José Antunes Nogueira',
    'Conjunto Habitacional Maria Paula Espósito',
    'Conjunto Habitacional Prefeito Jair Ferreira Duarte Júnior',
    'Cristóvão',
    'Desdobro Araçoiabinha',
    'Desdobro de José Pinto',
    'Estância Las Vegas',
    'Evidence Residencial',
    'Farias',
    "Fazenda D'Oeste I",
    "Fazenda D'Oeste II",
    "Fazenda D'Oeste III",
    'Green Gold Residence',
    'Guaxinduva',
    'Iperó-Mirim',
    'Itinga',
    'Jardim Arco Verde',
    'Jardim Dalila',
    'Jardim Ercília',
    'Jardim Escócia',
    'Jardim Flora',
    'Jardim Garret',
    'Jardim Laura',
    'Jardim Maria da Glória',
    'Jardim Master',
    'Jardim Mirantes de Ipanema',
    'Jardim Nossa Senhora Aparecida',
    'Jardim Nossa Senhora Salete',
    'Jardim Perlamar',
    'Jardim Planalto',
    'Jardim Residencial Lago da Serra',
    'Jardim Santa Cruz',
    'Jardim Tonelli',
    'Jardim Villa Real',
    'Jardim Village Saint Charbel',
    'Jundiacanga',
    'Jundiaquara',
    'Loteamento Jardim Floriano',
    'Nova Araçoiaba',
    'Parque Monte Bianco',
    'Parque Monte Líbano',
    'Portal Araçoiaba',
    'Portal do Sabiá',
    'Portão Grande',
    'Pouso dos Boiadeiros',
    'Quintas de Campo Largo',
    'Recanto Aldeville',
    'Recanto Gran Ville',
    'Recanto Ipanema do Meio',
    'Recanto Rio Verde',
    'Residencial Alvorada',
    'Residencial Aquarius',
    'Residencial Cerejeiras',
    'Residencial Haras Pavão',
    'Residencial Nova Canaã',
    'Residencial Pomares',
    'Residencial Primavera',
    'Retiro',
    'Riacho Fundo',
    'Rio Verde',
    'Terras de Araçoiaba',
    'Terras de Camapuã',
    'Terras de San Felippe',
    'Terras do Sol Poente',
    'Vale Verde',
    'Világio di San Francesco',
    'Village Araçoiaba',
    'Village da Serra',
    'Village Ipanema I',
    'Village Ipanema II',
    'Villagio Brunelli',
    'Villágio Santa Clara',
  ],
  Iperó: [
    'Bela Vista',
    'Campos de Vileta (George Oetterer)',
    'Capuavinha',
    'CDHU Iperó',
    'Centro',
    'Chácaras Guarapiranga',
    'Distrito Industrial',
    'George Oetterer (Bacaetava)',
    'Horto Florestal Bela Vista',
    'Jardim Alvorada (George Oetterer)',
    'Jardim das Alamandas',
    'Jardim Irene',
    'Jardim Novo Horizonte',
    'Jardim Santa Cruz',
    'Jardim Sartorelli',
    'Jardim Vitorino',
    'Narita Park',
    'Portal de Iperó',
    'Portal do Cedro',
    'Residencial Jardim Nova Bacaetava',
    'Vale das Orquídeas',
    'Vila do Depósito',
    'Vila Nova Era (Bacaetava)',
    'Vila Santo Antônio',
    'Vila Vital',
  ],
  'Porto Feliz': [
    'Agrovila CAIC',
    'Aldeia dos Laranjais',
    'Altos do Jequitibá',
    'Avecuia',
    'Bambu',
    'Bananal do Avecuia',
    'Belo Alto',
    'Campo Real',
    'Canguera',
    'Centro',
    'Centro Prisional',
    'Chácara Bazzo',
    'Chácara de Recreio a Morada do Sol',
    'Chácara Deléu',
    'Chácara Nestor',
    'Chácara Sanches',
    'Cidade Jardim',
    'Cidade Nova Bandeirantes',
    'Colônia Rodrigo Silva',
    'Condomínio Vila das Palmeiras',
    'Conjunto Habitacional Agostinho Alcalá',
    'Conjunto Habitacional Benedito José Diana',
    'Conjunto Habitacional Eugênio Motta',
    'Conjunto Habitacional Fortunato Fioravante Angelieri',
    'Conjunto Habitacional Residencial Bello',
    'Convívio do Santo',
    'Distrito Industrial',
    'Distrito Industrial Dimas de Marco',
    'Distrito Industrial Guerini',
    'Distrito Industrial Itaqui',
    'Estância Araruna',
    'Fazenda Boa Vista I',
    'Fazenda Boa Vista II',
    'Gramadinho',
    'Indaiatuba',
    'Jardim Araritaguaba',
    'Jardim Bandeirantes',
    'Jardim Bela Fonte',
    'Jardim Bela Vista',
    'Jardim Borba Gato',
    'Jardim Brasil',
    'Jardim Esplanada',
    'Jardim Excelsior',
    'Jardim Ivone',
    'Jardim Julita',
    'Jardim Martelli',
    'Jardim Morumbi',
    'Jardim Porto City',
    'Jardim Porto Feliz',
    'Jardim Porungal',
    'Jardim Primavera',
    'Jardim Rolando Giuli',
    'Jardim Santa Cruz',
    'Jardim Santa Eliza',
    'Jardim Santa Rosa',
    'Jardim Santa Terezinha',
    'Jardim São Bento',
    'Jardim São José',
    'Jardim São Pedro',
    'Jardim Seckler',
    'Jardim Sofia',
    'Jardim Tendá',
    'Jardim Vista Alegre',
    'Loteamento Residencial Bora Bora',
    'Loteamento Residencial Terras do Porto',
    'Palmital',
    'Parque Residencial Água Branca',
    'Parque Residencial Célia Maria',
    'Parque Residencial Rafael Alcalá',
    'Parque Residencial São Marcos',
    'Piquirá',
    'Ponte',
    'Ponte Grande',
    'Portal das Monções',
    'Portal dos Bandeirantes I',
    'Portal dos Bandeirantes II',
    'Portal Vale do Sol',
    'Portal Ville Flamboyant',
    'Recanto Avecuia',
    'Recanto dos Bandeirantes',
    'Recanto Monções',
    'Recanto Portela',
    'Residencial Bepim',
    'Residencial Cambará',
    'Residencial Carlos Brugnaro',
    'Residencial Humberto Martelli',
    'Residencial Jandira Diez Alcalá',
    'Residencial Madalena',
    'Residencial Montana Ville',
    'Residencial Olívio Barbosa',
    'Residencial Portal Ville Ipê',
    'Residencial Porto Feliz',
    'Residencial Santa Clara',
    'Residencial São Francisco',
    'Santa Marina',
    'Santo Augusto',
    'São Carlos',
    'São Francisco',
    'Soamim',
    'Spring Valley',
    'Tanque Seco',
    'Terras de San Rafael',
    'Terras de San Thomé',
    'Tupinambá',
    'Vila Alcalá',
    'Vila América',
    'Vila Angélica',
    'Vila Manduqinha',
    'Vila Maria',
    'Vila Martelli',
    'Vila Progresso',
    'Vila Tuani',
    'Village Porto Feliz',
  ],
};

/** Cada bairro com a cidade, para que dois "Centro" não se confundam. */
export const NEIGHBORHOOD_SUGGESTIONS: string[] = Object.entries(NEIGHBORHOODS_BY_CITY).flatMap(
  ([city, neighborhoods]) => neighborhoods.map((neighborhood) => `${neighborhood}, ${city}`),
);
